/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.btl_java_n9.view;

import com.mycompany.btl_java_n9.view.Panel_Teacher.View_DiemTP;
import javax.swing.JOptionPane;
import com.mycompany.btl_java_n9.view.Panel_Teacher.View_DiemTP;
import com.mycompany.btl_java_n9.view.Panel_Teacher.View_DiemThi;
import com.mycompany.btl_java_n9.view.Panel_Teacher.View_PhanHoi;
import com.mycompany.btl_java_n9.view.Panel_Teacher.View_GioiThieu;

/**
 *
 * @author NguyenVanHung
 */
public class View_Teacher extends javax.swing.JFrame {

    /**
     * Creates new form View_Teacher
     */
    public View_Teacher() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        diemTPBtn = new javax.swing.JButton();
        diemThiBtn = new javax.swing.JButton();
        phanHoiBtn = new javax.swing.JButton();
        tablePanel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        dangxuatBtn = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        diemTPBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/I_32/icons8-old-vmware-logo-32.png"))); // NOI18N
        diemTPBtn.setText("Điểm TP");
        diemTPBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diemTPBtnActionPerformed(evt);
            }
        });

        diemThiBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/I_32/icons8-old-vmware-logo-32.png"))); // NOI18N
        diemThiBtn.setText("Điểm Thi");
        diemThiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diemThiBtnActionPerformed(evt);
            }
        });

        phanHoiBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/I_32/icons8-facebook-messenger-32 (1).png"))); // NOI18N
        phanHoiBtn.setText("Phản hồi");
        phanHoiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phanHoiBtnActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Chào mừng bạn đến với giao diện quản lí điểm sinh viên\n");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/I_64/icons8-settings (1).gif"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(24, 24, 24))
        );

        tablePanel.addTab("Home", jPanel1);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/I_42/icons8-person-40.png"))); // NOI18N
        jLabel1.setText("Xin chào! Teacher");

        jMenu1.setText("Chức năng");

        dangxuatBtn.setText("Đăng xuất");
        dangxuatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangxuatBtnActionPerformed(evt);
            }
        });
        jMenu1.add(dangxuatBtn);

        jMenuItem1.setText("Thoát");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Trợ giúp");

        jMenuItem2.setText("Giới thiệu");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(177, 177, 177)
                        .addComponent(diemTPBtn)
                        .addGap(18, 18, 18)
                        .addComponent(diemThiBtn)
                        .addGap(18, 18, 18)
                        .addComponent(phanHoiBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tablePanel)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diemTPBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diemThiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phanHoiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablePanel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void diemTPBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diemTPBtnActionPerformed
        // TODO add your handling code here:
        tablePanel.remove(0);
        tablePanel.addTab("Điểm TP", new View_DiemTP());
    }//GEN-LAST:event_diemTPBtnActionPerformed

    private void dangxuatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangxuatBtnActionPerformed
        // TODO add your handling code here:
        int ch=JOptionPane.showConfirmDialog(this, "Ban có chắc chắn muốn đăng xuất ?");
        if(ch==JOptionPane.YES_OPTION ){
            new DangNhap().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_dangxuatBtnActionPerformed

    private void diemThiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diemThiBtnActionPerformed
        // TODO add your handling code here:
        tablePanel.remove(0);
        tablePanel.addTab("Điểm Thi", new View_DiemThi());
    }//GEN-LAST:event_diemThiBtnActionPerformed

    private void phanHoiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phanHoiBtnActionPerformed
        // TODO add your handling code here:
        tablePanel.remove(0);
        tablePanel.addTab("Phản hồi", new View_PhanHoi());
    }//GEN-LAST:event_phanHoiBtnActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        tablePanel.remove(0);
        tablePanel.addTab("Giới thiệu", new View_GioiThieu());
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        int ch=JOptionPane.showConfirmDialog(this, "Ban có chắc chắn muốn thoát ?");
        if(ch==JOptionPane.YES_OPTION ){
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Teacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem dangxuatBtn;
    private javax.swing.JButton diemTPBtn;
    private javax.swing.JButton diemThiBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton phanHoiBtn;
    private javax.swing.JTabbedPane tablePanel;
    // End of variables declaration//GEN-END:variables
}
