/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.btl_java_n9.view.Panel_Admin;

import com.mycompany.btl_java_n9.entity.PhanHoi;

/**
 *
 * @author Administrator
 */
public class ChiTietPhanHoi extends javax.swing.JPanel {

    /**
     * Creates new form ChiTietPhanHoi
     */
    public ChiTietPhanHoi(PhanHoi p) {
        initComponents();
        masv.setText(p.getNguoiGui());
        tg.setText(p.getNgayGui());
        nd.setText(p.getNoiDung());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        masv = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tg = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        nd = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/I_32/icons8-person-32.png"))); // NOI18N
        jLabel1.setText("Mã sinh viên: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, 27));

        masv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(masv, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 155, 27));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/I_32/icons8-old-vmware-logo-32.png"))); // NOI18N
        jLabel3.setText("Thời gian:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, -1, 27));

        tg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(tg, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 170, 27));

        nd.setColumns(20);
        nd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nd.setRows(5);
        jScrollPane1.setViewportView(nd);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 560, 140));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/I_32/icons8-remove-32 (1).png"))); // NOI18N
        jLabel2.setText("Nội dung:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, 27));

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/I_16/icons8-log-out-16.png"))); // NOI18N
        jButton1.setText("Trở về");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 300, 100, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 1, 870, 420));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jPanel1.removeAll();
        jPanel1.add(new HomThu(), new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 400));
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel masv;
    private javax.swing.JTextArea nd;
    private javax.swing.JLabel tg;
    // End of variables declaration//GEN-END:variables
}
