package com.mycompany.btl_java_n9.view.Panel_Admin;

import java.awt.LayoutManager;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class SuaSV extends javax.swing.JPanel {
   
    /**
     * Creates new form SuaSV
     */
    public SuaSV() {
        initComponents();
        bang.add(new DanhSachSV(), new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 400));
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bang = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/I_32/icons8-edit-profile-32.png"))); // NOI18N
        jLabel1.setText("Sua Thong Tin Sinh Vien");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, -1, -1));

        bang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(bang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 730, 370));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bang;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
