/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.btl_java_n9.view.Panel_Admin;

import com.mycompany.btl_java_n9.controller.admin.ThemSV_con;
import com.mycompany.btl_java_n9.data_acess.ChuyenSinhVien;
import com.mycompany.btl_java_n9.data_acess.SinhVien_AdminDTA;
import com.mycompany.btl_java_n9.entity.SinhVien_HoSo;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Administrator
 */
public class SuaTTSV extends javax.swing.JPanel {
    ArrayList<SinhVien_HoSo>list=new SinhVien_AdminDTA().docfile();
   
    /**
     * Creates new form SuaTTSV
     */
    public SuaTTSV() {
        initComponents();
        setMacDinh();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        hoten = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pass = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        diachi = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        khoa = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        lop = new javax.swing.JComboBox<>();
        ngaysinh = new javax.swing.JFormattedTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/I_16/icons8-name-16.png"))); // NOI18N
        jLabel2.setText("Họ tên:");
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 70, 80, -1));
        jPanel1.add(hoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 70, 190, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/I_16/icons8-forgot-password-16.png"))); // NOI18N
        jLabel3.setText("Pass:");
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 120, 70, -1));
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 190, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/I_16/icons8-info-popup-16 (1).png"))); // NOI18N
        jLabel4.setText("Ngay sinh:");
        jLabel4.setToolTipText("");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 170, 100, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/I_16/icons8-adress-16.png"))); // NOI18N
        jLabel5.setText("Địa chỉ: ");
        jLabel5.setToolTipText("");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 70, -1, -1));

        diachi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hà Giang", "Cao Bằng", "Bắc Kạn", "Lạng Sơn", "Tuyên Quang", "Thái Nguyên", "Phú Thọ", "Bắc Giang", "Quảng Ninh", "Lào Cai", "Yên Bái", "Điện Biên", "Hoà Bình", "Lai Châu", "Sơn La", "Bắc Ninh", "Hà Nam", "Hà Nội", "Hải Dương", "Hải Phòng", "Hưng Yên", "Nam Định", "Ninh Bình", "Thái Bình", "Vĩnh Phúc." }));
        diachi.setMaximumSize(new java.awt.Dimension(52, 32767));
        diachi.setMinimumSize(new java.awt.Dimension(52, 20));
        diachi.setPreferredSize(new java.awt.Dimension(52, 20));
        jPanel1.add(diachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 70, 160, 25));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/I_16/icons8-refresh-16.png"))); // NOI18N
        jButton1.setText("Cập nhật");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 238, 110, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/I_16/icons8-close-16.png"))); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 238, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/I_16/icons8-class-16 (1).png"))); // NOI18N
        jLabel6.setText("Khoa:");
        jLabel6.setToolTipText("");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 120, -1, -1));

        khoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CNTT", "HTTT", "KHMT", "KTPM" }));
        khoa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                khoaItemStateChanged(evt);
            }
        });
        jPanel1.add(khoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 120, 130, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/I_16/icons8-class-16.png"))); // NOI18N
        jLabel7.setText("Lớp:");
        jLabel7.setToolTipText("");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, -1));

        lop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CNTT1", "CNTT2" }));
        jPanel1.add(lop, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 130, -1));
        jPanel1.add(ngaysinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 190, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 850, 370));
    }// </editor-fold>//GEN-END:initComponents

    private void khoaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_khoaItemStateChanged
        new ThemSV_con().setKhoa(khoa, lop);
    }//GEN-LAST:event_khoaItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         SinhVien_HoSo s=new ChuyenSinhVien().docfile();
         int ch = 0;
        if(new ThemSV_con().kiemtraText(hoten, pass, ngaysinh)){
           for(int i=0;i<list.size();++i){
               if(s.getMasv().equals(list.get(i).getMasv())){
                   ch=i;
                   break;
               }
           }
            s.setHoten(hoten.getText());
            s.setPass(pass.getText());
            s.setNgaysinh(ngaysinh.getText());
            s.setDiachi((String) diachi.getSelectedItem());
            s.setKhoa((String) khoa.getSelectedItem());
            s.setLop((String) lop.getSelectedItem());
            list.set(ch, s);
            JOptionPane.showMessageDialog(this, "Cập nhật thành công! ");
            new SinhVien_AdminDTA().ghifile(list);
            jPanel1.removeAll();
            jPanel1.add(new DanhSachSV(), new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 400));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       setMacDinh();
    }//GEN-LAST:event_jButton2ActionPerformed

    public void setDiachi(String diachi) {
        this.diachi.setSelectedItem(diachi); 
    }

    public void setHoten(String hoten) {
        this.hoten.setText(hoten); 
    }

    public void setKhoa(String khoa) {
        this.khoa.setSelectedItem(khoa);
    }

    public void setLop(String lop) {
        this.lop.setSelectedItem(lop);
    }

    public void setNgaysinh(String ngaysinh) {
        this.ngaysinh.setText(ngaysinh);
    }

    public void setPass(String pass) {
        this.pass.setText(pass);
    }

private void setMacDinh() {
        SinhVien_HoSo s=new ChuyenSinhVien().docfile();
        hoten.setText(s.getHoten());
        pass.setText(s.getPass());
        this.setDiachi(s.getDiachi());
        this.setKhoa(s.getKhoa());
        this.setLop(s.getLop());
        try {
            MaskFormatter mf=new MaskFormatter("##/##/####");
            DefaultFormatterFactory dff=new DefaultFormatterFactory(mf);
            ngaysinh.setFormatterFactory(dff);
            ngaysinh.setText(s.getNgaysinh());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Loi: "+ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> diachi;
    private javax.swing.JTextField hoten;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> khoa;
    private javax.swing.JComboBox<String> lop;
    private javax.swing.JFormattedTextField ngaysinh;
    private javax.swing.JTextField pass;
    // End of variables declaration//GEN-END:variables
}
